SampleApp2::Application.routes.draw do
  # This was automatically generated by the 'rails generate controller Users new'
  # but it does not follow REST architectural conventions
  get "users/new"
  
  # create the match definition for the users controller
  match '/signup', :to => 'users#new'
  
  # match automatically creates named routes for use in the controllers and views:
      #   about_path => '/about'
      #   about_url => 'http://localhost:3000/about'
  match '/contact', :to => 'pages#contact' # route link to the pages_controller
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  # Defines the root as the Home page
      # root_path => '/'
      #       root_url => 'http://localhost:3000/'
  root :to => 'pages#home'
  
  # get "pages/home"
  # 
  # get "pages/contact"
  # 
  # get "pages/help"
  # 
  # get "pages/about"
  # 


  

  # The priority is based upon order of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end
